version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_minimal
    restart: unless-stopped
    environment:
      POSTGRES_USER: apiuser_test
      POSTGRES_PASSWORD: apipass_test
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: cpp-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=apiuser_test
      - DB_PASSWORD=apipass_test
      - DB_NAME=apidb

volumes:
  pgdata:
